Updated to Jupyter protocol v5
zabirauf/icsharp pull request #49
Opened 2018-08-05 00:09 UTC by wildart

Update to Jupyter message specification v5 which allows to run the kernel on recent version of Jupyter Lab/Notebook. Closes #44.

2018-08-05 01:23 UTC, zabirauf commented
Thanks a lot for the PR. I’ll take a look at it and merge it.

2018-08-17 21:43 UTC, wildart commented
It looks like Travis chokes on dependency tests not related to this PR.

2018-08-20 07:24 UTC, zabirauf requested changes

2018-08-20 07:24 UTC, zabirauf commented on Kernel/Helpers/SignatureValidator.cs
> -		public bool IsValidSignature (Message message)
Why is this removed?

2018-08-20 07:24 UTC, zabirauf commented on Kernel/ScriptEngine/IoPubConsole.cs
> -            Dictionary<string, object> data = new Dictionary<string, object>()
Just wondering whats the reason for changing it.

2018-08-20 07:24 UTC, zabirauf commented on Kernel/Shell/ExecuteRequestHandler.cs
> +                dynamic errorContent = new JObject();
Dont use dynamics, instead do the following
```
JObject errorContent = new JObject
{
  {"executiion_count", this.executionCount},
  {"ename", ex.GetType().ToString()},
  {"evalue", ex.Message}
};
```

2018-08-20 07:24 UTC, zabirauf commented on Kernel/Shell/ExecuteRequestHandler.cs
> +                var ex = results.CompileError != null ? results.CompileError : results.ExecuteError;
Can you put this in a separate function?

2018-08-20 07:24 UTC, zabirauf commented on Messages/Message.cs
> +        [JsonIgnoreAttribute]
We are not sending signature any more?

2018-09-23 04:19 UTC, merged